ntra-7: Implement Difference method in the existing calculator.
CodelineAtyab/ClassicCalc pull request #16
Opened 2023-08-02 08:09 UTC by ahmedhh33

this is a difference method in prac.js file

2023-08-02 09:14 UTC, omranali2111 approved these changes

2023-08-06 05:32 UTC, WhatIsFun requested changes
You shouldnt change anything in the index.html file please fix it

2023-08-06 07:00 UTC, alhabsi16 approved these changes

2023-08-06 07:00 UTC, CodelineAtyab approved these changes

2023-08-06 07:01 UTC, SalimAlsaadi approved these changes

2023-08-06 07:01 UTC, osamaline1229 approved these changes

2023-08-06 07:02 UTC, ahmedhh33 commented
> You shouldnt change anything in the index.html file please fix it

done

2023-08-06 07:03 UTC, WhatIsFun approved these changes

2023-08-06 07:03 UTC, merged